### ISSUE TITLE
Unable to import TargetResponse from 'agenteval.targets'

### ISSUE THREAD

**Issue by tengfone** [awslabs/agent-evaluation#52]
- A reproducible test case or series of steps
Failed when importing "from agenteval.targets import BaseTarget, TargetResponse"
- The version of our code being used
agent-evaluation 0.1.0
- Any modifications you've made relevant to the bug
NIL
- Anything unusual about your environment or deployment
NIL, tested on AWS Sagemaker, Google Collab and local venv python. All python version 3.10.6 / 3.11.4

Whenever I import the line `from agenteval.targets import BaseTarget, TargetResponse` , i get the error:

```
ImportError: cannot import name 'TargetResponse' from 'agenteval.targets' (/opt/conda/lib/python3.10/site-packages/agenteval/targets/__init__.py)
```

Upon checking the source file, the TargetResponse does not exist on the folder level, importing this way works:
```
from agenteval.targets import BaseTarget
from agenteval.target_response import TargetResponse
```

If possible please update the user guide [here](https://awslabs.github.io/agent-evaluation/targets/custom_targets/#:~:text=json%0A%0Aimport%20requests-,from%20agenteval.targets%20import%20BaseTarget%2C%20TargetResponse,-class%20MyAPITarget)

**Comment by tonykchen** [comment]
@tengfone Thanks for raising this! We will work on the fix.
